github.com:
    users:
        Pastafarista:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Pastafarista
